Lab02_Mvc_Valverde_B/Models/ClsDispensador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab02_Mvc_Valverde_B.Models
{
    public class ClsDispensador
    {
        public double monto {  get; set; }
        public int b10 { get; set; }

        public int b20 { get; set; }
        public int b50 { get; set; }
        public int b100 { get; set; }
        public int b1 { get; set; }
        public int b2 { get; set; }
        public int b5 { get; set; }

        public double b010 { get; set; }
        public double b020 { get; set; }
        public double b050 { get; set; }

        public int cantidad { get; set; }
    }
}

Lab02_Mvc_Valverde_B/Models/ClsPersonas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab02_Mvc_Valverde_B.Models
{
    public class ClsPersonas
    {
        public string DNI { get; set; }
        public string Apellido { get; set; }
        public string Nombre { get; set; }
        public bool Sexo { get; set; }
        public int Edad { get; set; }
        public double Talla { get; set; }
        public int Peso { get; set; }




    }
}

Lab02_Mvc_Valverde_B/Controllers/DispensadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab02_Mvc_Valverde_B.Models;

namespace Lab02_Mvc_Valverde_B.Controllers
{
    public class DispensadorController : Controller
    {
        // GET: Dispensador
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CalcularBilletes(ClsDispensador objDispensador)
        {
            if (objDispensador.monto > 0)
            {
                objDispensador.b100=Convert.ToInt32(objDispensador.monto/100);
                objDispensador.b50 = Convert.ToInt32(objDispensador.monto%100)/50;
                objDispensador.b20 = Convert.ToInt32((objDispensador.monto % 100)%50) / 20;
                objDispensador.b10 = Convert.ToInt32(((objDispensador.monto % 100) % 50)%20) / 10;
                objDispensador.b5 = Convert.ToInt32((((objDispensador.monto % 100) % 50) % 20) % 10)/5;
                objDispensador.b2 = Convert.ToInt32(((((objDispensador.monto % 100) % 50) % 20) % 10) % 5)/2;
                objDispensador.b1 = Convert.ToInt32((((((objDispensador.monto % 100) % 50) % 20) % 10) % 5) % 2)/1;
                objDispensador.b050 = (((((((objDispensador.monto % 100) % 50) % 20) % 10) % 5) % 2) % 1) / 0.5;
                objDispensador.b020 =((((((((objDispensador.monto % 100) % 50) % 20) % 10) % 5) % 2) % 1) % 0.5) / 0.2;
                objDispensador.b010 = (((((((((objDispensador.monto % 100) % 50) % 20) % 10) % 5) % 2) % 1)% 0.5) % 0.2) /0.1;
                objDispensador.cantidad = Convert.ToInt32(objDispensador.b100 + objDispensador.b50 + objDispensador.b20 + objDispensador.b10 + objDispensador.b5 + objDispensador.b2 + objDispensador.b1 +
                    objDispensador.b050 + objDispensador.b020 + objDispensador.b010);
            }
            else
            {
                Response.Write("<script language=javascript>alert('Ingrese monto correcto');</script>");
                return View("Index");
            }
            return View("CalcularBilletes", objDispensador);
        }
    }
}

Lab02_Mvc_Valverde_B/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab02_Mvc_Valverde_B.Models;

namespace Lab02_Mvc_Valverde_B.Controllers
{
    public class PersonaController : Controller
    {
        // GET: Persona
        public ActionResult MostrarUno()
        {
            ClsPersonas objPersona = new ClsPersonas();

            objPersona.DNI = "123456789";
            objPersona.Apellido = "Valverde";
            objPersona.Nombre = "Jean";
            objPersona.Sexo = true;
            objPersona.Edad = 21;
            objPersona.Peso = 80;
            objPersona.Talla = 1.52;
            return View(objPersona);
         
        }
        public ActionResult ListarTodo()
        {
            List<ClsPersonas> Lista = new List<ClsPersonas>();
            ClsPersonas objPersona1 = new ClsPersonas();

            objPersona1.DNI = "123456789";
            objPersona1.Apellido = "Valverde";
            objPersona1.Nombre = "Jean";
            objPersona1.Sexo = true;
            objPersona1.Edad = 21;
            objPersona1.Peso = 80;
            objPersona1.Talla = 1.70;

            Lista.Add(objPersona1);

            ClsPersonas objPersona2 = new ClsPersonas();

            objPersona2.DNI = "1122333";
            objPersona2.Apellido = "Cano";
            objPersona2.Nombre = "Sucso";
            objPersona2.Sexo = false;
            objPersona2.Edad = 21;
            objPersona2.Peso = 65;
            objPersona2.Talla = 1.80;

            Lista.Add(objPersona2);

            ClsPersonas objPersona3 = new ClsPersonas();

            objPersona3.DNI = "31313132";
            objPersona3.Apellido = "Chambilla";
            objPersona3.Nombre = "Josue";
            objPersona3.Sexo = false;
            objPersona3.Edad = 21;
            objPersona3.Peso = 60;
            objPersona3.Talla = 1.75;

            Lista.Add(objPersona3);

            ClsPersonas objPersona4 = new ClsPersonas();

            objPersona4.DNI = "2221122";
            objPersona4.Apellido = "Rivera";
            objPersona4.Nombre = "Jonny";
            objPersona4.Sexo = true;
            objPersona4.Edad = 21;
            objPersona4.Peso = 66;
            objPersona4.Talla = 1.85;

            Lista.Add(objPersona4);

            ClsPersonas objPersona5 = new ClsPersonas();

            objPersona5.DNI = "2221122";
            objPersona5.Apellido = "Jarro";
            objPersona5.Nombre = "Josue";
            objPersona5.Sexo = true;
            objPersona5.Edad = 21;
            objPersona5.Peso = 69;
            objPersona5.Talla = 1.79;

            Lista.Add(objPersona5);

            return View(Lista);
        }
    }
}

Lab02_Mvc_Valverde_B/Views/Dispensador/CalcularBilletes.cshtml
@model Lab02_Mvc_Valverde_B.Models.ClsDispensador
@{
    ViewBag.Title = "CalcularBilletes";
}

<title>Dispensador de Billetes</title>
<body>
<div>
    <center>
        <h1>Dispensador de Billetes</h1>
        <br />
        <label>Monto: </label>@Model.monto<br />
        <br />
        <label>Billete de 100:</label>@Model.b100<br />
        <label>Billete de 50:</label>@Model.b50<br />
        <label>Billete de 20:</label>@Model.b20<br />
        <label>Billete de 10:</label>@Model.b10<br />
        <label>Moneda de 5: </label>@Model.b5<br />
        <label>Moneda de 2: </label>@Model.b2<br />
        <label>Moneda de 1: </label>@Model.b1<br />
        <label>Moneda de 0.5: </label>@Model.b050<br />
        <label>Moneda de 0.2: </label>@Model.b020<br />
        <label>Moneda de 0.1: </label>@Model.b010<br />
        <br />
        <br />
        <label>Cantidad:</label>@Model.cantidad<br />
    </center>
</div>
</body>>

Lab02_Mvc_Valverde_B/Views/Dispensador/Index.cshtml
@model Lab02_Mvc_Valverde_B.Models.ClsDispensador
@{
    ViewBag.Title = "Index";
}

<title>Index</title>
<body>
    <div>
        <CENTER>
            <h1>Dispensador de Billetes</h1>
            <br />
            <br />
            @using (Html.BeginForm("CalcularBilletes","Dispensador", FormMethod.Post))
            {
                @Html.Label("Ingrese Monto:")
                @Html.EditorFor(Model=>Model.monto)<br />
                
                <input type="submit" value="Calcular"/>

            }
        </CENTER>
    </div>
</body>>

Lab02_Mvc_Valverde_B/Views/Persona/ListarTodo.cshtml
@model IEnumerable<Lab02_Mvc_Valverde_B.Models.ClsPersonas>
@{
    ViewBag.Title = "ListarTodo";
    int numero = 1;
}

<h2><center>ListarTodo</center></h2>
<body>
    <div>
        <center>
            <h1>Lista de personas</h1>
            <br />
            <table border="1" bordercolor="#0000FF">
                <tr>
                    <th>OrdenLista</th>>
                    <th>DNI:</th>
                    <th>Apellidos:</th>
                    <th>Nombre:</th>
                    <th>Talla:</th>
                    <th>Edad:</th>
                    <th>Sexo:</th>
                    <th>Peso:</th>
                    </tr>
                @foreach(var item in Model)
            {
                <tr>
                    <td>@(numero++)</td>
                    <td>@Html.DisplayFor(model=>item.DNI)</td>
                    <td>@Html.DisplayFor(model => item.Apellido)</td>
                    <td>@Html.DisplayFor(model => item.Nombre)</td>
                    <td>@Html.DisplayFor(model => item.Talla)</td>
                    <td>@Html.DisplayFor(model => item.Edad)</td>
                    <td>@Html.DisplayFor(model => item.Sexo)</td>
                    <td>@Html.DisplayFor(model => item.Peso)</td>
                </tr>
            }
</table>


        </center>
    </div>

</body>

Lab02_Mvc_Valverde_B/Views/Persona/MostrarUno.cshtml
@model Lab02_Mvc_Valverde_B.Models.ClsPersonas
@{
    Layout = null;
}
<!Doctype html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Mostrar Uno</title>
    </head>
    <body>
        <center>
        <div>
            <h1>
                <label>DNI: </label>@Model.DNI<br />
                <label>Nombre: </label>@Model.Nombre<br />
                <label>Apellido: </label>@Model.Apellido<br />
                <label>Sexo: </label>@Model.Sexo<br />
                <label>Talla: </label>@Model.Talla<br />
                <label>Peso: </label>@Model.Peso<br />
                <label>Edad: </label>@Model.Edad<br />
            </h1>
            </div>
            </center>
    </body>
</html>
<h2>MostrarUno</h2>

Lab02_Mvc_Valverde_B/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>